### 로그인 (accessToken 획득)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "employeeEmail": "admin@company.com",
  "password": "$2a$10$examplehashedpassword"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### 루트 부서 등록 (parentDepartmentId = null)
POST http://localhost:8080/api/v1/organization/department
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "parentDepartmentId": null,
  "departmentName": "경영지원본부",
  "teamName": "null",
  "depth": "L0"
}

### 하위 부서 등록 (parentDepartmentId 지정)
POST http://localhost:8080/api/v1/organization/department
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "parentDepartmentId": 1774588409082208,
  "departmentName": "개발본부",
  "teamName": "백엔드팀-2",
  "depth": "L2"
}

### 부서 등록 실패 - 부서명 누락 (400 Bad Request)
POST http://localhost:8080/api/v1/organization/department
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "parentDepartmentId": null,
  "departmentName": "",
  "teamName": "null",
  "depth": "L0"
}

### 부서 등록 실패 - 인증 없음 (401 Unauthorized)
POST http://localhost:8080/api/v1/organization/department
Content-Type: application/json

{
  "parentDepartmentId": null,
  "departmentName": "경영지원본부",
  "teamName": "null",
  "depth": "L0"
}
