### 로그인 (accessToken 획득)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "employeeEmail": "admin@seto.com",
  "password": "admin123!"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### 사원 등록
POST http://localhost:8080/api/v1/organization/employee
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "departmentId": 1774590584056408,
  "employeeName": "김신우",
  "employeeEmail": "sinseon2000@company.com",
  "employeePhone": "010-1234-5678",
  "employeeAddress": "서울시 강남구 테헤란로 123",
  "employeeEmergencyContact": "010-9876-5432",
  "employeePassword": "password123!",
  "employeeRole": "ADMIN",
  "employeeStatus": "ACTIVE",
  "employeeTier": "S"
}

### 사원 등록 실패 - 필수 항목 누락 (400 Bad Request)
POST http://localhost:8080/api/v1/organization/employee
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "departmentId": 177459058403,
  "employeeName": "ㅇㄷㅇㄷ",
  "employeeEmail": "hong@company.com",
  "employeePhone": "010-1234-5678",
  "employeeAddress": "서울시 강남구",
  "employeeEmergencyContact": "010-9876-5432",
  "employeePassword": "password123!",
  "employeeRole": "WORKER",
  "employeeStatus": "ACTIVE",
  "employeeTier": "B"
}
